repository:
  name: hyperledger
  description: Hyperledger is a Collaborative Project at The Linux Foundation.
  homepage: https://www.hyperledger.org
  default_branch: gh-pages
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
